#:schema node_modules/wrangler/config-schema.json
name = "minimalist-blog"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add your environment variables here

[[assets]]
directory = ".open-next/assets"
binding = "ASSETS"
